---

#- hosts: sparkmaster
- name: start spark cluster
  shell: /var/bigdata/spark/sbin/start-all.sh
  args:
    executable: /bin/bash 
  tags: 
    - start_cluster  
    - master

- name: stop spark clusterA
  shell: /var/bigdata/spark/sbin/stop-all.sh
  args:
    executable: /bin/bash 
  tags: 
    - stop_cluster
    - master



