
metadata:
    name: docker
    format: "Lava-Test-Shell Test Definition 1.0"
    description: "Automates deployment of containerized applications"
    maintainer:
        - liu_caili@hoperun.com
    scope:
        - virtualization
    os:
        - centos
        - ubuntu
    devices:
        - d03
        - d05
    level: 1
    totalcase:
        centos: 21
        ubuntu: 21

run:
    steps:
        - "cd auto-test/virtualization/virtual/docker; ./docker.sh; cd -"
parse:
    pattern: "^(?!.+ED)(?P<test_case_id>\\w+)\\s+(?P<result>\\w+)\\s+\\d$"
    fixupdict:
        FAIL: fail
        PASS: pass

