---

- name: judge SPARK_HOME
  shell: 'env|grep SPARK_HOME'
  register: ret 
  ignore_errors: yes
  tags: spark 

- name: include deploy spark 
  include: deploy.yml
  when: ret.rc != 0 
  tags: spark 


