---
# tasks file for zk-ansible

- name: judge zookeeper package is exist
  stat:
    path: ~/zookeeper.tar.gz
  register: zkIsExist
  tags: install

- debug: msg={{ zkIsExist }}

- name: download zookeeper bin package
  get_url:
    url: '{{ zookeeper_package }}'
    dest: ~/zookeeper.tar.gz
  when: not zkIsExist.stat.exists
  tags: install

- name: make zookeeper work direction
  file:
    path: '{{ zk_home }}'
    state: directory
  tags: install
- debug: msg= {{ zk_home }}
  tags: install

- name: archive zookeeper.tar.gz
  unarchive:
    src: ~/zookeeper.tar.gz 
    dest: '{{ zk_home }}'
    creates: '{{ zk_home }}/zookeeper-{{ zk_version }}/conf/zoo.cfg'
    copy: no
  register: zk 
  tags: install


- name: judge ZK_HOME is exist ~/.bashrc 
  shell:  grep ZK_HOME ~/.bashrc 
  ignore_errors: True
  register: zk_env
  tags: install

- name: set zookeeper env
  shell: path={{ zk_home }} ; path=$path/zookeeper-{{ zk_version  }} ; 
      echo "export ZK_HOME=$path" >> ~/.bashrc;  
      echo 'export PATH=$PATH:$ZK_HOME' >> ~/.bashrc;
      source ~/.bashrc 
  when: zk_env.rc != 0 
  tags: install


- name: copy zoo.cfg to targter
  template: 
    src: '{{ zk_cfg }}'
    dest: '{{ zk_home }}/zookeeper-{{ zk_version }}/conf/zoo.cfg'
    force: yes 
  notify:
      restart zk 
  tags: install


