---

- name: judge zk is install
  stat:
    path: '{{ zk_home }}/zookeeper-{{ zk_version }}/bin'
  register: zkInsatll
  tags:
    - install
    - start 
    - stop 
    - restart 

- name: deploy zk node 
  include_tasks: deploy.yml
  when: not  zkInsatll.stat.exists
  tags: 
    - install 
    - start 

- name: start zk server
  include_tasks: startServer.yml 
  tags: 
    - start 
  when:  zkInsatll.stat.exists

- name: stop server
  include_tasks: stopServer.yml
  tags: 
    - stop 
  when:  zkInsatll.stat.exists

- name: update zoo.cfg and restart server
  include_tasks: restartServer.yml
  tags:
    - restart
  when:  zkInsatll.stat.exists
    


