---
 
- name: copy zoo.cfg to targter
  template: 
    src: '{{ zk_cfg }}'
    dest: '{{ zk_home }}/zookeeper-{{ zk_version }}/conf/zoo.cfg'
    force: yes 
  notify:
      restart zk 
  tags: restart 
